#mysql 参数配置
[mysql]
debug = true
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 3306
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
db_name = "GMS"
# 连接参数
parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

[etcd]
addrs = ["127.0.0.1:2379"]
register_ttl = 15
register_interval = 10

[micro]
name = "gms.role.srv.service"
version = "1"